services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.13.40
    container_name: clickhouse-container
    environment:
      - CLICKHOUSE_INIT_TIMEOUT=60
      - CLICKHOUSE_UID=101
      - CLICKHOUSE_GID=101
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-storage:/var/lib/clickhouse
      - clickhouse-storage:/var/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - wh-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    user: root
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE

volumes:
  clickhouse-storage: {}

networks:
  wh-net: